# Generated by Django 5.1.3 on 2025-03-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
